embedding_size: 512
feat_embed_dim: 64

n_layers: [1, 2]
dropout: [0.3, 0.5]
reg_weight: [1.0, 1e-01, 1e-02, 1e-03, 1e-04, 1e-05]
cl_weight: 2.0


use_neg_sampling: False

hyper_parameters: ["n_layers", "reg_weight", "dropout"]

