embedding_size: 512
latent_size: 64
feat_embed_dim: 64

is_federated: True
is_multimodal_model: True

learner: 'adam'

fusion_module: 'moe' # 'moe', 'sum', 'attention', 'mlp', 'gate'
num_heads: 8 # number of heads in the attention module

use_neg_sampling: True

# hyper_parameters: [ "alpha", "beta", "lr", "l2_reg" ]
# # hyper_parameters: [ "lr", "l2_reg" ]

#hyper_parameters: [ ]
alpha: 1e-4
beta: 1e-2
# lr: 1e-1
# l2_reg: 1e-4

# hyper_parameters: [ "alpha", "beta", "lr", "l2_reg" ]
hyper_parameters: [ "lr", "l2_reg" ]

# hyper_parameters: []

#lr: 0.001
#l2_reg: 1e-4

# alpha: [ 1e-1,1e-2,1e-3,1e-4 ]
# beta: [ 1e-1,1e-2,1e-3,1e-4 ]

lr: [ 0.01,0.005,0.001 ]
l2_reg: [ 1e-4,1e-5 ]
